name: Build, Squash, and Push Docker Image

on:
  schedule:
    # Chạy hàng ngày lúc 0h giờ Việt Nam (UTC+7)
    - cron: "0 17 * * *"
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  build-squash-push:
    runs-on: ubuntu-22.04

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Cài đặt docker-squash
      - name: Install docker-squash
        run: |
          sudo curl -sL https://github.com/shinsenter/docker-squash/raw/main/docker-squash.sh -o /usr/local/bin/docker-squash.sh
          sudo chmod +x /usr/local/bin/docker-squash.sh

      # Build và push image ban đầu
      - name: Build and push initial Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial
          platforms: linux/amd64,linux/arm64

      # Squash image
      - name: Squash Docker image
        run: |
          docker pull bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial
          docker-squash.sh bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial -t bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial-squashed

      # Build và push image đã squash
      - name: Build and push squashed Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial-squashed
          platforms: linux/amd64,linux/arm64
