name: Build and Push Docker Image

on:
  schedule:
    # Tự động chạy hàng ngày vào 0h theo múi giờ Việt Nam (UTC+7)
    - cron: "0 17 * * *"
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      # Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build và push image đa nền tảng
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial
          platforms: linux/amd64,linux/arm64

      # ⭐ Thêm bước này để tạo commit rỗng, giữ cho repo "active"
      - name: Create empty commit to keep repo alive
        if: success()  # Chỉ chạy nếu các bước trước thành công
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Keep repo active for scheduled workflows"
          git push
