name: Build and Push Docker Image

on:
  schedule:
    - cron: "0 17 * * *"  # 17h UTC = 0h VN (UTC+7)
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:  # ⭐ Thêm quyền ghi vào repo
      contents: write

    steps:
      # Checkout code với đủ quyền
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Cần thiết để git push hoạt động

      # Các bước build Docker (giữ nguyên)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: bibica/wordpress-wp-cli-php8.4-fpm-alpine-minial
          platforms: linux/amd64,linux/arm64

      # Bước tạo commit rỗng (đã fix lỗi permission)
      - name: Create empty commit to keep repo alive
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .  # ⭐ Thêm bước này để stage changes (dù là empty)
          git commit --allow-empty -m "Keep repo active for scheduled workflows"
          git push
